# Ant
# Build your Java projects and run tests with Apache Ant.
# Add steps that save build artifacts and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: 'PS QA Agent pool'
  demands:
  - Agent.Name -equals qacon
  #vmImage: 'ubuntu-latest'

variables:
- name: trgtFolder
  value: develop

steps:
- script: echo '##vso[task.setvariable variable=trgtFolder]master'
  displayName: "Set the trgtFolder as master if the Build.SourceBranch = 'refs/heads/master' "
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

- script: echo $(trgtFolder)