# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'esriPointTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'ArcGIS-Runtime-SDK-iOS', '100.0.0'
  # Pods for esriPointTest

  target 'esriPointTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'esriPointTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
